# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test11():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_11(self):
    # Test name: 1 (1)
    # Step # | name | target | value | comment
    # 1 | open | / |  | 
    self.driver.get("https://www.google.com/")
    # 2 | setWindowSize | 1211x808 |  | 
    self.driver.set_window_size(1211, 808)
    # 3 | click | name=q |  | 
    self.driver.find_element(By.NAME, "q").click()
    # 4 | type | name=q | тестовый сценарий | 
    self.driver.find_element(By.NAME, "q").send_keys("тестовый сценарий")
    # 5 | click | id=lga |  | 
    self.driver.find_element(By.ID, "lga").click()
    # 6 | click | css=center:nth-child(1) > .gNO89b |  | 
    self.driver.find_element(By.CSS_SELECTOR, "center:nth-child(1) > .gNO89b").click()
    # 7 | click | name=q |  | 
    self.driver.find_element(By.NAME, "q").click()
    # 8 | type | name=q | hello world | 
    self.driver.find_element(By.NAME, "q").send_keys("hello world")
    # 9 | close |  |  | 
    self.driver.close()
  
