# Generated by Selenium IDE
from selenium import webdriver
from selenium.webdriver.common.by import By


class Test11:
    def setup_method(self, method):
        self.driver = webdriver.Firefox()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_11(self):
        # Test name: 1 (1)
        # Step # | name | target | value | comment
        # 1 | open | / |  |
        wd=self.driver
        wd.get("https://www.google.com/")
        # 2 | setWindowSize | 1211x808 |  |
        wd.set_window_size(1211, 808)
        # 3 | click | name=q |  |
        wd.find_element(By.NAME, "q").click()
        # 4 | type | name=q | тестовый сценарий |
        wd.find_element(By.NAME, "q").send_keys("тестовый сценарий")
        # 5 | click | id=lga |  |
        wd.find_element(By.ID, "lga").click()
        # 6 | click | css=center:nth-child(1) > .gNO89b |  |
        wd.find_element(By.CSS_SELECTOR, "center:nth-child(1) > .gNO89b").click()
        # 7 | click | name=q |  |
        wd.find_element(By.NAME, "q").click()
        # 8 | type | name=q | hello world |
        wd.find_element(By.NAME, "q").send_keys("hello world")
        # 9 | close |  |  |
        wd.close()
